### ISSUE TITLE
tensorflow_core.contrib.gan is gone in the tensorflow 1.15.2

### ISSUE THREAD

**Issue by ALearningProgrammer** [Octavian-ai/BigGAN-TPU-TensorFlow#10]
When I run the code, it shows the following error:

Traceback (most recent call last):
  File "main_tpu.py", line 62, in <module>
    main()
  File "main_tpu.py", line 58, in main
    get_estimator(args, gan, True))
  File "/content/BigGAN-TPU-TensorFlow/main_loop.py", line 33, in run_main_loop
    prefetch_inception_model()
  File "/content/BigGAN-TPU-TensorFlow/inception_score.py", line 17, in prefetch_inception_model
    calculate_inception_score(images)
  File "/content/BigGAN-TPU-TensorFlow/inception_score.py", line 45, in calculate_inception_score
    v_images = tf.contrib.gan.eval.preprocess_image(v_image_batch)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/lazy_loader.py", line 63, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorflow_core.contrib' has no attribute 'gan'

**Comment by davidhughhenrymack** [comment]
Hi,
I've not had time to maintain this codebase, sorry :/
